# Generated by Django 4.2.4 on 2023-10-17 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('province', models.CharField(choices=[('badakhshan', 'Badakhshan'), ('badghis', 'Badghis'), ('baghlan', 'Baghlan'), ('balkh', 'Balkh'), ('bamyan', 'Bamyan'), ('daykundi', 'Daykundi'), ('farah', 'Farah'), ('faryab', 'Faryab'), ('ghazni', 'Ghazni'), ('ghor', 'Ghor'), ('helmand', 'Helmand'), ('herat', 'Herat'), ('jowzjan', 'Jowzjan'), ('kabul', 'Kabul'), ('kandahar', 'Kandahar'), ('kapisa', 'Kapisa'), ('khost', 'Khost'), ('kunar', 'Kunar'), ('kunduz', 'Kunduz'), ('laghman', 'Laghman'), ('logar', 'Logar'), ('nangarhar', 'Nangarhar'), ('nimroz', 'Nimroz'), ('nuristan', 'Nuristan'), ('paktia', 'Paktia'), ('paktika', 'Paktika'), ('panjshir', 'Panjshir'), ('parwan', 'Parwan'), ('samangan', 'Samangan'), ('sar-e-pol', 'Sar-e Pol'), ('takhar', 'Takhar'), ('urozgan', 'Urozgan'), ('wardak', 'Wardak'), ('zabul', 'Zabul')], max_length=55)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('under_investigation', 'Under Investigation')], max_length=55)),
                ('complaint_type', models.CharField(choices=[('security', 'Security'), ('passport', 'Passport'), ('traffic', 'Traffic'), ('civil_registration', 'Civil Registration'), ('law_enforcement', 'Police and Enforcement'), ('corruption', 'Corruption'), ('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('employment', 'Employment'), ('personal_injury', 'Personal Injury'), ('discrimination', 'Discrimination'), ('other', 'Other')], max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.complaint')),
            ],
        ),
    ]
