# Generated by Django 4.2.4 on 2023-12-05 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attachments",
            new_name="Attachment",
        ),
    ]
