# Generated by Django 4.2.4 on 2023-10-22 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_attachments_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('under_investigation', 'Under Investigation'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=55),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('new', 'Your complaint was submitted successfully'), ('under_investigation', 'Your complaint is under investigation'), ('resolved', 'Your complaint has been resolved'), ('rejected', 'Your complaint has been rejected'), ('closed', 'Your complaint has been closed')], max_length=55)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
