# Generated by Django 4.2.4 on 2023-10-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_complaint_state_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="address",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="province",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="state",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="title",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="user",
        ),
        migrations.AddField(
            model_name="complaint",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("bribe_given", "Bribe Given"),
                    ("bribe_taken", "Bribe Taken"),
                ],
                max_length=55,
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
